package ProjectICP;

import audio.audio2;
import audio.audio3;
import audio.audio4;
import audio.audio5;
import audio.audio6;
import audio.audio7;
import audio.audio8;
import java.awt.*;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import java.awt.event.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 /*
 *
 * @author Admin
 */
public class Audio extends javax.swing.JFrame {

    /**
     * Creates new form Audio
     */
    public Audio() {
        getContentPane().setBackground(Color.PINK);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JButton();
        s2 = new javax.swing.JButton();
        s3 = new javax.swing.JButton();
        s4 = new javax.swing.JButton();
        s5 = new javax.swing.JButton();
        s6 = new javax.swing.JButton();
        s7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audio/music.png"))); // NOI18N
        jLabel1.setText("Garba Songs");

        s1.setBackground(new java.awt.Color(255, 255, 255));
        s1.setText("90_Non_Stop_Falguni_Pathak_(Gujarati_Garba)_By_Falguni_Pathak_1");
        s1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                s1MouseMoved(evt);
            }
        });
        s1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MouseExited(evt);
            }
        });
        s1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s1ActionPerformed(evt);
            }
        });

        s2.setBackground(new java.awt.Color(255, 255, 255));
        s2.setText("90_Non_Stop_Falguni_Pathak_(Gujarati_Garba)_By_Falguni_Pathak_2");
        s2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                s2MouseMoved(evt);
            }
        });
        s2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s2MouseExited(evt);
            }
        });
        s2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s2ActionPerformed(evt);
            }
        });

        s3.setBackground(new java.awt.Color(255, 255, 255));
        s3.setText("Aaj_Daldu_Jaai_Chatki");
        s3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                s3MouseMoved(evt);
            }
        });
        s3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s3MouseExited(evt);
            }
        });
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });

        s4.setBackground(new java.awt.Color(255, 255, 255));
        s4.setText("Gujrati-Garba-And-Dandiya-Non-Stop-Remix-1");
        s4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                s4MouseMoved(evt);
            }
        });
        s4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s4MouseExited(evt);
            }
        });
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });

        s5.setBackground(new java.awt.Color(255, 255, 255));
        s5.setText("Gujrati-Garba-And-Dandiya-Non-Stop-Remix-2");
        s5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                s5MouseMoved(evt);
            }
        });
        s5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s5MouseExited(evt);
            }
        });
        s5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s5ActionPerformed(evt);
            }
        });

        s6.setBackground(new java.awt.Color(255, 255, 255));
        s6.setText("Gujrati-Garba-And-Dandiya-Non-Stop-Remix-3");
        s6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                s6MouseMoved(evt);
            }
        });
        s6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s6MouseExited(evt);
            }
        });
        s6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s6ActionPerformed(evt);
            }
        });

        s7.setBackground(new java.awt.Color(255, 255, 255));
        s7.setText("Maa_Durga_Aarti");
        s7.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                s7MouseMoved(evt);
            }
        });
        s7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                s7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                s7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                s7MouseExited(evt);
            }
        });
        s7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s7ActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audio/boy.jpg"))); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/audio/girl.jpg"))); // NOI18N

        jButton1.setText("MENU");
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(510, 510, 510))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2)
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(s2)
                            .addComponent(s1)
                            .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s4, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s5, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s6, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s7, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(151, 151, 151)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(622, 622, 622)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(s1)
                            .addGap(41, 41, 41)
                            .addComponent(s2)
                            .addGap(46, 46, 46)
                            .addComponent(s3)
                            .addGap(45, 45, 45)
                            .addComponent(s4)
                            .addGap(49, 49, 49)
                            .addComponent(s5)
                            .addGap(53, 53, 53)
                            .addComponent(s6)
                            .addGap(52, 52, 52)
                            .addComponent(s7))
                        .addComponent(jLabel3))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void s1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s1ActionPerformed
        // TODO add your handling code here:
        try {
            loadNewWindow(new audio2());
        } catch (Exception ex) {
            Logger.getLogger(Audio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_s1ActionPerformed
    /*s1.addMouseListener(new MouseAdapter() {
         Color oldcolor = s1.getForeground();
         public void mouseEntered(MouseEvent me) {
            oldcolor = button.getForeground();
            button.setForeground(Color.red);
         }
         public void mouseExited(MouseEvent me) {
            button.setForeground(oldcolor);
         }
      });*/


    private void s5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s5ActionPerformed
        try {
            loadNewWindow(new audio6());
        } catch (Exception ex) {
            Logger.getLogger(Audio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_s5ActionPerformed

    private void s7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s7ActionPerformed
        try {
            loadNewWindow(new audio8());
        } catch (Exception ex) {
            Logger.getLogger(Audio.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_s7ActionPerformed

    void loadNewWindow(JFrame frame) {
        this.setVisible(false);
        this.dispose();
        frame.setVisible(true);
    }
    private void s7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s7MouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_s7MouseClicked

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        // TODO add your handling code here:
        try {
            loadNewWindow(new audio5());
        } catch (Exception ex) {
            Logger.getLogger(Audio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_s4ActionPerformed

    private void s6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s6ActionPerformed

        // TODO add your handling code here:
        try {
            loadNewWindow(new audio7());
        } catch (Exception ex) {
            Logger.getLogger(Audio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_s6ActionPerformed

    private void s2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s2ActionPerformed
        // TODO add your handling code here:
        try {
            loadNewWindow(new audio3());
        } catch (Exception ex) {
            Logger.getLogger(Audio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_s2ActionPerformed

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        // TODO add your handling code here:
        try {
            loadNewWindow(new audio4());
        } catch (Exception ex) {
            Logger.getLogger(Audio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_s3ActionPerformed

    private void MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEntered
        // TODO add your handling code here:
        s1.setBackground(Color.gray);
    }//GEN-LAST:event_MouseEntered

    private void MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseExited
        // TODO add your handling code here:
        s1.setBackground(Color.white);
    }//GEN-LAST:event_MouseExited

    private void s2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseEntered
        // TODO add your handling code here:
        s2.setBackground(Color.gray);
    }//GEN-LAST:event_s2MouseEntered

    private void s2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseExited
        // TODO add your handling code here:
       s2.setBackground(Color.white);
    }//GEN-LAST:event_s2MouseExited

    private void s3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseEntered
        // TODO add your handling code here:
        s3.setBackground(Color.gray);
    }//GEN-LAST:event_s3MouseEntered

    private void s3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseExited
        // TODO add your handling code here:
        s3.setBackground(Color.white);
    }//GEN-LAST:event_s3MouseExited

    private void s4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s4MouseEntered
        // TODO add your handling code here:
        s4.setBackground(Color.gray);
    }//GEN-LAST:event_s4MouseEntered

    private void s4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s4MouseExited
        // TODO add your handling code here:
        s4.setBackground(Color.white);
    }//GEN-LAST:event_s4MouseExited

    private void s5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s5MouseEntered
        // TODO add your handling code here:
        s5.setBackground(Color.gray);
    }//GEN-LAST:event_s5MouseEntered

    private void s5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s5MouseExited
        // TODO add your handling code here:
        s5.setBackground(Color.white);
    }//GEN-LAST:event_s5MouseExited

    private void s6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s6MouseEntered
        // TODO add your handling code here:
        s6.setBackground(Color.gray);
    }//GEN-LAST:event_s6MouseEntered

    private void s6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s6MouseExited
        // TODO add your handling code here:
        s6.setBackground(Color.white);
    }//GEN-LAST:event_s6MouseExited

    private void s7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s7MouseEntered
        // TODO add your handling code here:
        s7.setBackground(Color.gray);
    }//GEN-LAST:event_s7MouseEntered

    private void s7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s7MouseExited
        // TODO add your handling code here:
        s7.setBackground(Color.white);
    }//GEN-LAST:event_s7MouseExited

    private void s1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s1MouseMoved
        // TODO add your handling code here:
          s1.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
    }//GEN-LAST:event_s1MouseMoved

    private void s2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s2MouseMoved
        // TODO add your handling code here:
        s2.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_s2MouseMoved

    private void s3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s3MouseMoved
        // TODO add your handling code here:
        s3.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_s3MouseMoved

    private void s4MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s4MouseMoved
        // TODO add your handling code here:
        s4.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_s4MouseMoved

    private void s5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s5MouseMoved
        // TODO add your handling code here:
        s5.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_s5MouseMoved

    private void s6MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s6MouseMoved
        // TODO add your handling code here:
        s6.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_s6MouseMoved

    private void s7MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_s7MouseMoved
        // TODO add your handling code here:
        s7.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_s7MouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        // TODO add your handling code here:
         jButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          loadNewWindow(new Menu12());
    }//GEN-LAST:event_jButton1ActionPerformed

     
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Audio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Audio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Audio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Audio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Audio().setVisible(true);
            }
        });
        /* JavaFX_Mediaaudio j=new  JavaFX_Mediaaudio();
        Stage p=new Stage();
        try {
            j.start(p);
        } catch (Exception ex) {
            Logger.getLogger(Audio.class.getName()).log(Level.SEVERE, null, ex);
        }*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton s1;
    private javax.swing.JButton s2;
    private javax.swing.JButton s3;
    private javax.swing.JButton s4;
    private javax.swing.JButton s5;
    private javax.swing.JButton s6;
    private javax.swing.JButton s7;
    // End of variables declaration//GEN-END:variables
}
